automotores/urls.py
from django.conf.urls import patterns, include, url

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    url(r'^$', 'apps.epa.views.login', name='login'),
    url(r'^$', 'apps.epa.views.logout', name='logout'),
    # url(r'^automotores/', include('automotores.foo.urls')),
    url(r'^automotores/', include('apps.epa.urls')),
    # Uncomment the admin/doc line below to enable admin documentation:
    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    url(r'^admin/', include(admin.site.urls)),
)

apps/epa/forms.py
#! /usr/bin/python
# -*- encoding: utf-8 -*-

from django import forms 
from apps.epa.models import *
from django.forms import ModelForm, TimeField
from django.contrib import admin
from django.utils import timezone 
from django.conf import settings
from django.contrib.auth.models import  Group,Permission,User
from django.contrib.admin import widgets
from django.contrib.admin.widgets import FilteredSelectMultiple
from django.forms.widgets import CheckboxSelectMultiple
from django.core.exceptions import ValidationError
attrs_dict = { 'class': 'required' }

class LoginForm(forms.Form):
	usuario = forms.CharField(widget=forms.TextInput(attrs=dict({'class':'required span9','placeholder':'Usuario'})))
	password = forms.CharField(widget=forms.PasswordInput(attrs=dict({'class':'required span9','placeholder':'Contraseña'}), render_value=False))


class CiudadesForm(forms.ModelForm):
    descripcion = forms.CharField(widget=forms.TextInput(attrs=dict({'class':'required form-control','placeholder':'Descripcion'})),required=True)
    class Meta:
        model = RefCiudades

class DepartamentosForm(forms.ModelForm):
    descripcion = forms.CharField(required=True)
    class Meta:
        model = RefDepartamentos

class ProvinciasForm(forms.ModelForm):
    descripcion = forms.CharField(required=True)
   
    class Meta:
        model = RefProvincia


class PaisesForm(forms.ModelForm):
    descripcion = forms.CharField(required=True)
    class Meta:
		model = RefPaises

class UnidadesForm(forms.ModelForm):
    descripcion = forms.CharField(widget=forms.TextInput(attrs=dict({'class':'required form-control','placeholder':'Descripcion'})),required=True)
    ciudad = forms.ModelChoiceField(widget=forms.Select(attrs=dict({'class':'required form-control'})), queryset= RefCiudades.objects.all()  )
    class Meta:
        model = UnidadesRegionales
 
class DependenciasForm(forms.ModelForm):
    descripcion = forms.CharField(widget=forms.TextInput(attrs=dict({'class':'required form-control','placeholder':'Descripcion'})),required=True)
    ciudad = forms.ModelChoiceField(widget=forms.Select(dict({'class':'required form-control'})), queryset= RefCiudades.objects.all()  )
    unidades_regionales = forms.ModelChoiceField(widget = forms.Select(dict({'class':'required form-control'})), queryset= UnidadesRegionales.objects.all())

    
    class Meta:
        model = Dependencias     

class TipoVehiculoForm(forms.ModelForm):
    descripcion = forms.CharField(widget=forms.TextInput(attrs=dict({'class':'required form-control','placeholder':'Descripcion'})),required=True)

    class Meta:
        model = TipoVehiculo

class EstadoMovilForm(forms.ModelForm):
    descripcion = forms.CharField(widget=forms.TextInput(attrs=dict({'class':'required form-control','placeholder':'Descripcion'})),required=True)

    class Meta:
        model = EstadoMovil

class RefTrademarkForm(forms.ModelForm):
    descripcion = forms.CharField(widget=forms.TextInput(attrs=dict({'class':'required form-control','placeholder':'Descripcion'})),required=True)    

    class Meta:
        model = RefTrademark

class RefModelosForm(forms.ModelForm):
    marca     = forms.ModelChoiceField(widget = forms.Select(dict({'class':'required form-control'})), queryset= RefTrademark.objects.all())
    descripcion = forms.CharField(widget=forms.TextInput(attrs=dict({'class':'required form-control','placeholder':'Descripcion'})),required=True)    

    class Meta:
        model = RefModelos

class VehiculoForm(forms.ModelForm):
    dominio     = forms.CharField(widget=forms.TextInput(attrs=dict({'class':'required form-control','placeholder':'AAH-113','required':'required'})),required=True)    
    anio        = forms.CharField(widget=forms.TextInput(attrs=dict({'class':'form-control','placeholder':'2014'})))    
    nmotor      = forms.CharField(widget=forms.TextInput(attrs=dict({'class':'form-control','placeholder':'Numero de motor'})))    
    nchasis     = forms.CharField(widget=forms.TextInput(attrs=dict({'class':'form-control','placeholder':'Numero de chasis'})))    
    modelo      = forms.ModelChoiceField(widget = forms.Select(dict({'class':'required form-control'})), queryset= RefModelos.objects.all())
    idmarca     = forms.ModelChoiceField(widget = forms.Select(dict({'class':'required form-control'})), queryset= RefTrademark.objects.all())

    class Meta:
        model = Vehiculo

class MovilForm(forms.ModelForm):
    unidad_regional     = forms.ModelChoiceField(widget = forms.Select(dict({'class':'required form-control'})), queryset= UnidadesRegionales.objects.all())
    dependencia         = forms.ModelChoiceField(widget = forms.Select(dict({'class':'required form-control'})),queryset=Dependencias.objects.all())
    tipo_vehiculo       = forms.ModelChoiceField(widget = forms.Select(dict({'class':'required form-control'})),queryset=TipoVehiculo.objects.all())
    registro_interno    = forms.CharField(widget=forms.TextInput(attrs=dict({'class':'required form-control','placeholder':'Registro Interno','required':'required'})),required=True)    


    class Meta:
        model = Movil

class MovilEstadoForm(forms.ModelForm):
    estado          = forms.ModelChoiceField(widget = forms.Select(dict({'class':'required form-control'})),queryset=EstadoMovil.objects.all())
    observaciones   = forms.CharField(widget = forms.Textarea(dict({'class':'required form-control'})))
    class Meta:
        exclude = ('movil')
        model = MovilEstado

templates/referencias/dependencias.html
{% extends 'base.html' %}

{% block cuerpo %}

		<div class="col-md-6 column">
			<div class="panel panel-primary">
				<div class="panel-heading">
					<h3 class="panel-title">
						ABM de Dependencias
					</h3>
				</div>
				<div class="panel-body">
				{% if dependencia %}
					<form role="form" action="{% url 'dependencia' dependencia.id %}" method="post">{% csrf_token %}
				{% else %}
					<form role="form" action="{% url 'dependencias' %}" method="post">{% csrf_token %}
				{% endif %}
						<div>
							 <label for="id_ciudad">Ciudad </label>{{form.ciudad}}
							 <a id="agregarCiudad" href="#ciudadNueva" role="button" class="btn btn-info btn-xs" data-toggle="modal">Agregar Ciudad</a>
						</div>
						<div class="form-group">
							 <label for="id_unidades_regionales">Unidad Regional </label>{{form.unidades_regionales}}
						</div>
						
						<div class="form-group">
							 <label for="id_descripcion">Descripcion</label>{{form.descripcion}}
						</div>
						<button type="submit" class="btn btn-success btn-small pull-right">Guardar</button>	
					</form>
				</div>
				<div class="panel-footer">
					
				</div>
			</div>
		</div>
		<div class="col-md-6 column">
			<table class="table table-bordered table-hover table-condensed" id="table" name="table">
				<thead>
					<tr>
						<th>
							#
						</th>
						<th>
							Unidad Regional
						</th>
						<th>
							Dependencia
						</th>
						<th>
							Ciudad
						</th>
						<th>
						</th>
					</tr>
				</thead>
				<tbody>
				{% for depe in dependencias %}
					<tr>
						<td>
							{{depe.id}}
						</td>
						<td>
							{{depe.unidades_regionales}}
						</td>
						<td>
							{{depe.descripcion}}
						</td>
						<td>
							{{depe.ciudad}}
						</td>
						<td>
							<center><a href="{% url 'dependencia' depe.id %}"><i class="glyphicon glyphicon-pencil"></i></a></center>
						</td>
					</tr>
				{% endfor %}
				</tbody>
			</table>
			<div class="modal fade" id="ciudadNueva" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
								<div class="modal-dialog">
									<div class="modal-content">
										<div class="modal-header">
											 <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
											<h4 class="modal-title" id="myModalLabel">
												Agregar Ciudad
											</h4>
										</div>
										<form role="form" action="{% url 'agregaciudad' %}" method="post">
										<div class="modal-body">
											
												<div class="form-group">
													 <label for="id_descripcion">Descripcion</label>{{ciudades.descripcion}}
													 <input type="hidden" name="formulario" id="formulario" value="dependencias">
												</div>											
										</div>
										<div class="modal-footer">
											 <button type="button" class="btn btn-default" data-dismiss="modal">Cerrar</button> <button type="submit" class="btn btn-success">Guardar</button>{% csrf_token %}
										</div>
										</form>
									</div>
									
								</div>
								
							</div>
		</div>
	
{% endblock %}

templates/referencias/estadomovil.html
{% extends 'base.html' %}

{% block cuerpo %}

		<div class="col-md-6 column">
			<div class="panel panel-primary">
				<div class="panel-heading">
					<h3 class="panel-title">
						ABM de Estados de movil
					</h3>
				</div>
				<div class="panel-body">
				{% if estado %}
					<form role="form" action="{% url 'estadomovil' estado.id %}" method="post">{% csrf_token %}
				{% else %}
					<form role="form" action="{% url 'estadosmovil' %}" method="post">{% csrf_token %}
				{% endif %}
					
						<div class="form-group">
							 <label for="id_descripcion">Descripcion</label>{{form.descripcion}}
						</div>
						<button type="submit" class="btn btn-success btn-small pull-right">Guardar</button>	
					</form>
				</div>
				<div class="panel-footer">
					
				</div>
			</div>
		</div>
		<div class="col-md-6 column">
			<table class="table table-bordered table-hover table-condensed" id="table" name="table">
				<thead>
					<tr>
						<th>
							#
						</th>
						<th>
							Estado
						</th>
						<th>
						</th>
					</tr>
				</thead>
				<tbody>
				{% for e in estados %}
					<tr>
						<td>
							{{e.id}}
						</td>
						<td>
							{{e.descripcion}}
						</td>
						<td>
							<center><a href="{% url 'estadomovil' e.id %}"><i class="glyphicon glyphicon-pencil"></i></a></center>
						</td>
					</tr>
				{% endfor %}
				</tbody>
			</table>
			
		</div>
	
{% endblock %}

templates/referencias/marcas.html
{% extends 'base.html' %}

{% block cuerpo %}

		<div class="col-md-6 column">
			<div class="panel panel-primary">
				<div class="panel-heading">
					<h3 class="panel-title">
						ABM de Marcas
					</h3>
				</div>
				<div class="panel-body">
				{% if marca %}
					<form role="form" action="{% url 'marca' marca.id %}" method="post">{% csrf_token %}
				{% else %}
					<form role="form" action="{% url 'marcas' %}" method="post">{% csrf_token %}
				{% endif %}
					
						<div class="form-group">
							 <label for="id_descripcion">Descripcion</label>{{form.descripcion}}
						</div>
						<button type="submit" class="btn btn-success btn-small pull-right">Guardar</button>	
					</form>
				</div>
				<div class="panel-footer">
					
				</div>
			</div>
		</div>
		<div class="col-md-6 column">
			<table class="table table-bordered table-hover table-condensed" id="table" name="table">
				<thead>
					<tr>
						<th>
							#
						</th>
						<th>
							Marca
						</th>
						<th>
						</th>
					</tr>
				</thead>
				<tbody>
				{% for m in marcas %}
					<tr>
						<td>
							{{m.id}}
						</td>
						<td>
							{{m.descripcion}}
						</td>
						<td>
							<center><a href="{% url 'marca' m.id %}"><i class="glyphicon glyphicon-pencil"></i></a></center>
						</td>
					</tr>
				{% endfor %}
				</tbody>
			</table>
			
		</div>
	
{% endblock %}

templates/referencias/modelos.html
{% extends 'base.html' %}

{% block cuerpo %}

		<div class="col-md-6 column">
			<div class="panel panel-primary">
				<div class="panel-heading">
					<h3 class="panel-title">
						ABM de Modelos
					</h3>
				</div>
				<div class="panel-body">
				{% if modelo %}
					<form role="form" action="{% url 'modelo' modelo.id %}" method="post">{% csrf_token %}
				{% else %}
					<form role="form" action="{% url 'modelos' %}" method="post">{% csrf_token %}
				{% endif %}
						<div class="form-group">
							 <label for="id_marca">Marca </label>{{form.marca}}
							 <!--a id="agregarCiudad" href="#ciudadNueva" role="button" class="btn btn-info btn-xs" data-toggle="modal">Agregar Ciudad</a-->
						</div>
						<div class="form-group">
							 <label for="id_descripcion">Descripcion</label>{{form.descripcion}}
						</div>
						<button type="submit" class="btn btn-success btn-small pull-right">Guardar</button>	
					</form>
				</div>
				<div class="panel-footer">
					
				</div>
			</div>
		</div>
		<div class="col-md-6 column">
			<table class="table table-bordered table-hover table-condensed" id="table" name="table">
				<thead>
					<tr>
						<th>
							#
						</th>
						<th>
							Marca
						</th>
						<th>
							Modelo
						</th>
						<th>
						</th>
					</tr>
				</thead>
				<tbody>
				{% for m in modelos %}
					<tr>
						<td>
							{{m.id}}
						</td>
						<td>
							{{m.marca}}
						</td>
						<td>
							{{m.descripcion}}
						</td>
						<td>
							<center><a href="{% url 'modelo' m.id %}"><i class="glyphicon glyphicon-pencil"></i></a></center>
						</td>
					</tr>
				{% endfor %}
				</tbody>
			</table>
			
		</div>
	
{% endblock %}

templates/referencias/tiposvehiculos.html
{% extends 'base.html' %}

{% block cuerpo %}

		<div class="col-md-6 column">
			<div class="panel panel-primary">
				<div class="panel-heading">
					<h3 class="panel-title">
						ABM de Tipos de Vehiculos
					</h3>
				</div>
				<div class="panel-body">
				{% if tipo %}
					<form role="form" action="{% url 'tipovehiculo' tipo.id %}" method="post">{% csrf_token %}
				{% else %}
					<form role="form" action="{% url 'tiposvehiculos' %}" method="post">{% csrf_token %}
				{% endif %}
					
						<div class="form-group">
							 <label for="id_descripcion">Descripcion</label>{{form.descripcion}}
						</div>
						<button type="submit" class="btn btn-success btn-small pull-right">Guardar</button>	
					</form>
				</div>
				<div class="panel-footer">
					
				</div>
			</div>
		</div>
		<div class="col-md-6 column">
			<table class="table table-bordered table-hover table-condensed" id="table" name="table">
				<thead>
					<tr>
						<th>
							#
						</th>
						<th>
							Tipo
						</th>
						<th>
						</th>
					</tr>
				</thead>
				<tbody>
				{% for t in tipos %}
					<tr>
						<td>
							{{t.id}}
						</td>
						<td>
							{{t.descripcion}}
						</td>
						<td>
							<center><a href="{% url 'tipovehiculo' t.id %}"><i class="glyphicon glyphicon-pencil"></i></a></center>
						</td>
					</tr>
				{% endfor %}
				</tbody>
			</table>
			
		</div>
	
{% endblock %}

templates/referencias/unidades.html
{% extends 'base.html' %}

{% block cuerpo %}

		<div class="col-md-6 column">
			<div class="panel panel-primary">
				<div class="panel-heading">
					<h3 class="panel-title">
						ABM de Unidades Regionales
					</h3>
				</div>
				<div class="panel-body">
				{% if unidad %}
					<form role="form" action="{% url 'unidad' unidad.id %}" method="post">{% csrf_token %}
				{% else %}
					<form role="form" action="{% url 'unidades' %}" method="post">{% csrf_token %}
				{% endif %}
						<div class="form-group">
							 <label for="id_ciudad">Ciudad </label>{{form.ciudad}}
							 <a id="agregarCiudad" href="#ciudadNueva" role="button" class="btn btn-info btn-xs" data-toggle="modal">Agregar Ciudad</a>
			

						</div>
						<div class="form-group">
							 <label for="id_descripcion">Descripcion</label>{{form.descripcion}}
						</div>
						<button type="submit" class="btn btn-success btn-small pull-right">Guardar</button>	
					</form>
				</div>
				<div class="panel-footer">
					
				</div>
			</div>
		</div>
		<div class="col-md-6 column">
			<table class="table table-bordered table-hover table-condensed" id="table" name="table">
				<thead>
					<tr>
						<th>
							#
						</th>
						<th>
							Unidad Regional
						</th>
						<th>
							Ciudad
						</th>
						<th>
							
						</th>
					</tr>
				</thead>
				<tbody>
				{% for uni in unidades %}
					<tr>
						<td>
							{{uni.id}}
						</td>
						<td>
							{{uni.descripcion}}
						</td>
						<td>
							{{uni.ciudad}}
						</td>
						<td>
							<center><a href="{% url 'unidad' uni.id %}"><i class="glyphicon glyphicon-pencil"></i></a></center>
						</td>
					</tr>
				{% endfor %}
				</tbody>
			</table>
			<div class="modal fade" id="ciudadNueva" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
								<div class="modal-dialog">
									<div class="modal-content">
										<div class="modal-header">
											 <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
											<h4 class="modal-title" id="myModalLabel">
												Agregar Ciudad
											</h4>
										</div>
										<form role="form" action="{% url 'agregaciudad' %}" method="post">
										<div class="modal-body">
											
												<div class="form-group">
													 <label for="id_descripcion">Descripcion</label>{{ciudades.descripcion}}
													 <input type="hidden" name="formulario" id="formulario" value="unidades">
												</div>											
										</div>
										<div class="modal-footer">
											 <button type="button" class="btn btn-default" data-dismiss="modal">Cerrar</button> <button type="submit" class="btn btn-success">Guardar</button>{% csrf_token %}
										</div>
										</form>
									</div>
									
								</div>
								
							</div>
		</div>
	
{% endblock %}