automotores/urls.py
from django.conf.urls import patterns, include, url

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    url(r'^$', 'apps.epa.views.login', name='login'),
    url(r'^$', 'apps.epa.views.logout', name='logout'),
    # url(r'^automotores/', include('automotores.foo.urls')),
    url(r'^automotores/', include('apps.epa.urls')),
    # Uncomment the admin/doc line below to enable admin documentation:
    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    url(r'^admin/', include(admin.site.urls)),
)

apps/epa/forms.py
#! /usr/bin/python
# -*- encoding: utf-8 -*-

from django import forms 
from apps.epa.models import *
from django.forms import ModelForm, TimeField
from django.contrib import admin
from django.utils import timezone 
from django.conf import settings
from django.contrib.auth.models import  Group,Permission,User
from django.contrib.admin import widgets
from django.contrib.admin.widgets import FilteredSelectMultiple
from django.forms.widgets import CheckboxSelectMultiple
from django.core.exceptions import ValidationError
attrs_dict = { 'class': 'required' }

class LoginForm(forms.Form):
	usuario = forms.CharField(widget=forms.TextInput(attrs=dict({'class':'required span9','placeholder':'Usuario'})))
	password = forms.CharField(widget=forms.PasswordInput(attrs=dict({'class':'required span9','placeholder':'Contraseña'}), render_value=False))


class CiudadesForm(forms.ModelForm):
    descripcion = forms.CharField(widget=forms.TextInput(attrs=dict({'class':'required form-control','placeholder':'Descripcion'})),required=True)
    class Meta:
        model = RefCiudades

class DepartamentosForm(forms.ModelForm):
    descripcion = forms.CharField(required=True)
    class Meta:
        model = RefDepartamentos

class ProvinciasForm(forms.ModelForm):
    descripcion = forms.CharField(required=True)
   
    class Meta:
        model = RefProvincia


class PaisesForm(forms.ModelForm):
    descripcion = forms.CharField(required=True)
    class Meta:
		model = RefPaises

class UnidadesForm(forms.ModelForm):
    descripcion = forms.CharField(widget=forms.TextInput(attrs=dict({'class':'required form-control','placeholder':'Descripcion'})),required=True)
    ciudad = forms.ModelChoiceField(widget=forms.Select(attrs=dict({'class':'required form-control'})), queryset= RefCiudades.objects.all()  )
    class Meta:
        model = UnidadesRegionales
 
class DependenciasForm(forms.ModelForm):
    descripcion = forms.CharField(widget=forms.TextInput(attrs=dict({'class':'required form-control','placeholder':'Descripcion'})),required=True)
    ciudad = forms.ModelChoiceField(widget=forms.Select(dict({'class':'required form-control'})), queryset= RefCiudades.objects.all()  )
    unidades_regionales = forms.ModelChoiceField(widget = forms.Select(dict({'class':'required form-control'})), queryset= UnidadesRegionales.objects.all())

    
    class Meta:
        model = Dependencias     

class TipoVehiculoForm(forms.ModelForm):
    descripcion = forms.CharField(widget=forms.TextInput(attrs=dict({'class':'required form-control','placeholder':'Descripcion'})),required=True)

    class Meta:
        model = TipoVehiculo

class EstadoMovilForm(forms.ModelForm):
    descripcion = forms.CharField(widget=forms.TextInput(attrs=dict({'class':'required form-control','placeholder':'Descripcion'})),required=True)

    class Meta:
        model = EstadoMovil

class RefTrademarkForm(forms.ModelForm):
    descripcion = forms.CharField(widget=forms.TextInput(attrs=dict({'class':'required form-control','placeholder':'Descripcion'})),required=True)    

    class Meta:
        model = RefTrademark

class RefModelosForm(forms.ModelForm):
    marca     = forms.ModelChoiceField(widget = forms.Select(dict({'class':'required form-control'})), queryset= RefTrademark.objects.all())
    descripcion = forms.CharField(widget=forms.TextInput(attrs=dict({'class':'required form-control','placeholder':'Descripcion'})),required=True)    

    class Meta:
        model = RefModelos

class VehiculoForm(forms.ModelForm):
    dominio     = forms.CharField(widget=forms.TextInput(attrs=dict({'class':'required form-control','placeholder':'AAH-113','required':'required'})),required=True)    
    anio        = forms.CharField(widget=forms.TextInput(attrs=dict({'class':'form-control','placeholder':'2014'})))    
    nmotor      = forms.CharField(widget=forms.TextInput(attrs=dict({'class':'form-control','placeholder':'Numero de motor'})))    
    nchasis     = forms.CharField(widget=forms.TextInput(attrs=dict({'class':'form-control','placeholder':'Numero de chasis'})))    
    modelo      = forms.ModelChoiceField(widget = forms.Select(dict({'class':'required form-control'})), queryset= RefModelos.objects.all())
    idmarca     = forms.ModelChoiceField(widget = forms.Select(dict({'class':'required form-control'})), queryset= RefTrademark.objects.all())

    class Meta:
        model = Vehiculo

class MovilForm(forms.ModelForm):
    unidad_regional     = forms.ModelChoiceField(widget = forms.Select(dict({'class':'required form-control'})), queryset= UnidadesRegionales.objects.all())
    dependencia         = forms.ModelChoiceField(widget = forms.Select(dict({'class':'required form-control'})),queryset=Dependencias.objects.all())
    tipo_vehiculo       = forms.ModelChoiceField(widget = forms.Select(dict({'class':'required form-control'})),queryset=TipoVehiculo.objects.all())
    registro_interno    = forms.CharField(widget=forms.TextInput(attrs=dict({'class':'required form-control','placeholder':'Registro Interno','required':'required'})),required=True)    


    class Meta:
        model = Movil

class MovilEstadoForm(forms.ModelForm):
    estado          = forms.ModelChoiceField(widget = forms.Select(dict({'class':'required form-control'})),queryset=EstadoMovil.objects.all())
    observaciones   = forms.CharField(widget = forms.Textarea(dict({'class':'required form-control'})))
    class Meta:
        exclude = ('movil')
        model = MovilEstado

templates/moviles/cargar_estado.html
{% extends 'moviles/movilbase.html' %}

{% block movilcuerpo %}
	<h3>Carga de Estado para el movil: {{movil}} <small> {{movil.unidad_regional}} {{movil.dependencia}}</small></h3>
	<form role="form" method="post" action="{% url 'cargar_estado' movil.id %}">{% csrf_token %}
		{{form.as_p}}
	
		<button type="submit" class="btn btn-success btn-sm pull-right">Guardar</button>
	</form>
	<br><br><hr>
	

	<table class="table table-bordered table-hover table-condensed" name="table" id="table">
				<thead>
					<tr>
						<th>
							#
						</th>
						<th>
							Estado
						</th>
						<th>
							Fecha
						</th>
					</tr>
				</thead>
				<tbody>
					{% for estado in estados %}
					<tr title="{{estado.observaciones}}">
						<td>
							{{estado.id}}
						</td>
						<td>
							{{estado.estado}}
						</td>
						<td>
							{{estado.fecha|date:'SHORT_DATE_FORMAT'}}
						</td>
					</tr>
					{% endfor %}
				</tbody>
			</table>
{% endblock %}

templates/moviles/estado.html
<!DOCTYPE html>
<html>
<head>
	<style type="text/css">
     .table {
	    border-collapse: collapse !important;
	  }
	  .table-bordered th,
	  .table-bordered td {
	    border: 1px solid #ddd !important;
	  }

    </style>
    <script language="Javascript">

  function imprSelec(nombre)

  {

  var ficha = document.getElementById(nombre);

  var ventimp = window.open(' ', 'popimpr');

  ventimp.document.write( ficha.innerHTML );

  ventimp.document.close();

  ventimp.print( );

  ventimp.close();

  } 

</script> 
</head>
<body>
<a href="javascript:imprSelec('imprimir')" >Imprimir</a> <a href="javascript:history.back(1)"> Volver </a>
<div id="imprimir">
<table style="width:100%;padding-top:20px">
		<tr>
			<td colspan="2"><img width="25%" src="{{STATIC_URL}}img/escudo.png" /></td>
			<td colspan="3"><center><h1>
				Estado de moviles policiales
			</h1></center></td>
			<td colspan="2"><p>
				Informacion Generada por: 
			</p></td>
		</tr>
	</table>
	<hr>
	<table style="width:100%;" class="table table-bordered">	
		<thead>
		<tr>
			<th>
				RI
			</th>
			<th>
				Tipo
			</th>
			<th>
				Marca
			</th>
			<th>
				Modelo
			</th>
			<th>
				A&ntilde;o
			</th>
			<th>
				Dominio
			</th>
			<th>
				Motor
			</th>
			<th>
				Chasis
			</th>
			<th>
				Destino
			</th>
			<th>
				Estado
			</th>
		</tr>
	</thead>
	<tbody >
		{% for movil in moviles %}
		<tr>
			<td>
				{{movil.registro_interno}}
			</td>
			<td>
				{{movil.tipo_vehiculo}}
			</td>
			<td> 
				{{movil.vehiculo.marca}}
			</td>
			<td>
				{{movil.vehiculo.modelo}}
			</td>
			<td>
				{{movil.vehiculo.anio}}
			</td>
			<td>
				{{movil.vehiculo.dominio}}
			</td>
			<td>
				{{movil.vehiculo.motor}}
			</td>
			<td>
				{{movil.vehiculo.chasis}}
			</td>
			<td>
				{{movil.unidad_regional}} - {{movil.dependencia}}
			</td>
			<td>
				{{movil.estados.all.0.estado}}
			</td>
		</tr>
		{% endfor %}
		</tbody>
	</table>
</div>
</body>
</html>

	


	<!--div class="container">
	<input type='button' class="btn btn-success" onclick='window.print();' value='Imprimir' />
	<br><hr>
	<div class="row clearfix">
		<div class="col-md-2 column">
			<img src="{{STATIC_URL}}img/escudo.png" />
		</div>
		<div class="col-md-6 column">
			<h1 class="text-center text-info">
				Estado de moviles policiales
			</h1>
		</div>
		<div class="col-md-4 column">
			<p>
				Informacion Generada por: 
			</p>
		</div>
	</div>
	<hr>
	<div class="row clearfix">
		<div class="col-md-12 column">
			<table class="table table-bordered table-hover table-condensed">
				<thead>
					<tr>
						<th>
							#
						</th>
						<th>
							Unidad Regional
						</th>
						<th>
							Dependencia
						</th>
						<th>
							Tipo Movil
						</th>
						<th>
							RI
						</th>
						<th>
							Estado
						</th>
						<th>
							Observaciones
						</th>
					</tr>
				</thead>
				<tbody>
					{% for movil in moviles %}
					<tr>
						<td>
							{{movil.id}}
						</td>
						<td>
							{{movil.unidad_regional}}
						</td>
						<td>
							{{movil.dependencia}}
						</td>
						<td>
							{{movil.tipo_vehiculo}}
						</td>
						<td>
							{{movil.registro_interno}}
						</td>
						<td>
							{{movil.estados.all.0.estado}}
						</td>
						<td>
							{{movil.estados.all.0.observaciones}}
						</td>
					</tr>
					{% endfor %}
				</tbody>
			</table>
		</div>
	</div>

</div-->	

templates/moviles/listado.html
{% extends 'moviles/movilbase.html' %}

{% block movilcuerpo %}
	<table class="table table-bordered table-hover table-condensed" name="table" id="table">
				<thead>
					<tr>
						<th>
							#
						</th>
						<th>
							Unidad Regional
						</th>
						<th>
							Dependencia
						</th>
						<th>
							Registro Interno
						</th>
						<th>
							Estado
						</th>
						<th>
							
						</th>
						<th>
							
						</th>
					</tr>
				</thead>
				<tbody>
					{% for movil in moviles %}
					<tr>
						<td>
							{{movil.id}}
						</td>
						<td>
							{{movil.unidad_regional}}
						</td>
						<td>
							{{movil.dependencia}}
						</td>
						<td>
							{{movil.registro_interno}}
						</td>
						<td>
							{{movil.estados.all.0.estado}}
						</td>
						<td>
							<a href="{% url 'modifica_movil' movil.id %}">	<i class="glyphicon glyphicon-pencil" data-toggle="tooltip" data-placement="right" title="Permite Modificar datos del Movil"></i></a>
						</td>
						<td>
							<a href="{% url 'cargar_estado' movil.id %}">	<i class="glyphicon glyphicon-edit" data-toggle="tooltip" data-placement="right" title="Permite Modificar el estado del Movil"></i></a>
						</td>
					</tr>
					{% endfor %}
				</tbody>
			</table>
		

{% endblock %}

templates/moviles/modifica_movil.html
{% extends 'moviles/movilbase.html' %}
{% block movilcuerpo %}

	<form role="form" method="post" action="{% url 'modifica_movil' movil.id %}">{% csrf_token %}
		<div class="form-group">
		 	 <label for="id_tipo_vehiculo">Tipo de vehiculo</label>{{form.tipo_vehiculo}}
		</div>
		<div class="form-group">
		 	 <label for="id_unidad_regional">Unidad Regional</label>{{form.unidad_regional}}
		</div>
		<div class="form-group">
		 	 <label for="id_dependencia">Dependencia</label>{{form.dependencia}}
		</div>
		<div class="form-group">
		 	 <label for="id_registro_interno">Registro Interno</label>{{form.registro_interno}}
		</div>
		<button type="submit" class="btn btn-success btn-sm pull-right">Guardar</button>
	</form>


{% endblock %}

templates/moviles/movilbase.html
{% extends 'base.html' %}
{% block cuerpo %}

	
		<div class="col-md-4 column">
			<div class="list-group">
				 <a href="{% url 'moviles' %}" class="list-group-item active">Móviles</a>
				<div class="list-group-item">
					<a href="{% url 'nuevo' %}"> Nuevo</a>
				</div>
				<div class="list-group-item">
					<a href="{% url 'listar' %}"> Listado de moviles </a>
				</div>
				<div class="list-group-item">
					<a href="{% url 'estado' %}"> Ver Estado moviles</a>
				</div>
				<!--div class="list-group-item">
					<a href=""> Ver estados</a>
				</div--> 
			</div>
		</div>
		<div class="col-md-8 column">

			{% if msg and not msg == '' %}
				<div class="alert alert-dismissable alert-info">
					 <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
					<strong>{{msg}}</strong> 
				</div>
			{% endif %}
			{% block movilcuerpo %}
				<p>En esta secci&oacute;n podra realizar la carga de moviles y el estado de los mismos.</p>
			{% endblock %}
		</div>
	

{% endblock %}

templates/moviles/nuevo.html
{% extends 'moviles/movilbase.html' %}
{% block movilcuerpo %}
	{% if movil %}
		<form role="form" method="post" action="{% url 'modifica_movil' movil.id %}">{% csrf_token %}
	{% else %}
		<form role="form" method="post" action="{% url 'nuevo' %}">{% csrf_token %}
	{% endif %}
		<h3>Datos del vehiculo</h3>
		<div class="form-group">
		 	 <label for="id_idmarca">Marca</label>{{form_vehiculo.idmarca}}
		</div>
		<div class="form-group">
		 	 <label for="id_modelo">Modelo</label>{{form_vehiculo.modelo}}
		</div>
		<div class="form-group">
		 	 <label for="id_anio">A&ntilde;o</label>{{form_vehiculo.anio}}
		</div>
		<div class="form-group">
		 	 <label for="id_nchasis">Numero de Chasis</label>{{form_vehiculo.nchasis}}
		</div>
		<div class="form-group">
		 	 <label for="id_nmotor">Numero de motor</label>{{form_vehiculo.nmotor}}
		</div>
		<div class="form-group">
		 	 <label for="id_dominio">Dominio</label>{{form_vehiculo.dominio}}
		</div>
		<hr class="divider">
		<h3>Datos del movil</h3>
		<div class="form-group">
		 	 <label for="id_tipo_vehiculo">Tipo de vehiculo</label>{{form.tipo_vehiculo}}
		</div>
		<div class="form-group">
		 	 <label for="id_unidad_regional">Unidad Regional</label>{{form.unidad_regional}}
		</div>
		<div class="form-group">
		 	 <label for="id_dependencia">Dependencia</label>{{form.dependencia}}
		</div>
		<div class="form-group">
		 	 <label for="id_registro_interno">Registro Interno</label>{{form.registro_interno}}
		</div>
		<button type="submit" class="btn btn-success btn-sm pull-right">Guardar</button>
	</form>


{% endblock %}